base_info:
  title: Tian
  author: TTT
  url: https://github.com/debugtheworldbot?tab=repositories
style:
  primary_color: "#0066CC"
  avatar: https://www.linkpicture.com/q/thumb-219022.jpg
  favicon: https://www.linkpicture.com/q/thumb-219022.jpg
  first_screen:
    enable: true
    description: 30% of myself made by code
  scroll:
    progress_bar: 
      enable: true
social_contact:
  enable: true
  links:
    github: https://github.com/debugtheworldbot
    twitter: https://twitter.com/_antivini_
code_copy:
  enable: true
home_article:
  category:
    enable: true
    limit: 3    
  tag:
    enable: true
    limit: 5  
post:
  word_count:
    enable: true
    wordcount: true
    min2read: true
  author_label:
    enable: true
    auto: false
    custom_label_list: ['codezera']
toc:
  enable: true
  number: true
  expand_all: true
  init_open: true
website_count:
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true
comment:
  enable: true
  use: valine  # values: valine | gitalk | twikoo

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid: Fj6gQz9zqpSIny6yIBPgQhj4-gzGzoHsz                
    appkey: BlmmvmISSVV7c3ci6xngKuvg
    placeholder: ğŸ˜œ å°½æƒ…åæ§½å§~
  pjax:
    enable: true